---
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.vscode/extensions.json:
  delete: true
.gitignore:
  required: &ignorepaths
    - '.onceover/'
    - '.covered.db'
.travis.yml:
  global_env:
  - COVERAGE=PartialSummary,Coveralls
  notifications:
    email:
      recipients:
      - gary@theclarkhome.com
      on_success: change # default: change
      on_failure: always # default: always
spec/spec_helper.rb:
  coverage_report: true
  mock_with: ':rspec'
  minimum_code_coverage_percentage: 100
  strict_level: ":warning"
  hiera_config: "hiera.yaml"
Rakefile:
  extras: 
  - FastGettext.default_text_domain = 'default-text-domain'
Gemfile:
  required:
    ':test':
      - gem: coveralls
      - gem: simplecov
      - gem: simplecov-console
      - gem: covered
  optional:
    ':development':
      - gem: 'github_changelog_generator'
        git: 'https://github.com/skywinder/github-changelog-generator'
        ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
        condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"
